project: Sweep-sct
name: Third-sweep-sct
description: TODO LR parameters; BatchNorm, LayerNorm; CNN num, kernel, pool; Layer-wise activation, d_model; Dataset
program: train.py
method: grid
metric:
  goal: minimize
  name: final_distance_error
parameters:
  num_vehicles:
    value: 6
  num_heads:
    value: 4
  d_model:
    values: [512, 1024]
  model:
    value: "sct"
  rnn_cell:
    value: "gru"
  dataset:
    value: "transformed_dataset"
  batch_size:
    value: 8
  epochs:
    value: 30
  frequency:
    value: 10
  activation:
    value: "tanh"
  dropout_rate:
    value: 0.3
  learning_rate:
    values: [0.0002, 0.0003]
  lr_schedule:
    value: True
  num_layers:
    values: [1, 2, 3]
# early_terminate:
#   type: hyperband
#   s: 3
#   eta: 2
#   min_iter: 4
